default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: postgres
  host: localhost

development:
  <<: *default
  database: r_cards_development

test:
  <<: *default
  database: r_cards_test

production:
  <<: *default
  database: r_cards_production
  username: r_cards
  password: <%= ENV["BACKEND_DATABASE_PASSWORD"] %>
